server:
  port: 9000 # 端口号
  context-path: /${spring.application.name}  # 访问路径，如果不配置，访问IP:端口号，配置后访问IP:端口号/${context-path}

spring:
  profiles:
    active: dev   # 当前被激活的环境，如果使用多环境配置时可以使用到
  application:
    name: pointQuartz    # 项目名称
  http:
    encoding:     # http编码
      force: true
      charset: UTF-8
      enabled: true
  freemarker:   # freemarker配置
    suffix: .ftl
    check-template-location: true
    defaultEncoding: UTF-8
    templateLoaderPath: classpath:/pointQuartz
    content-type: text/html
    request-context-attribute: request
logging:          # 日志
  level.root: info
  level.com.hexun.pointQuartz: debug
  path: logs/
  file: demo.log

---
##########################################################
###################  开发环境的profile  ##################
##########################################################
spring:
  profiles: dev
  datasource:       # mybatis 配置，使用druid数据源
    url: jdbc:mysql://192.168.4.96:3306/match_db?useUnicode=true&characterEncoding=UTF-8
    username: applicationuser
    password: 1234qwer
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

---
##########################################################
###################  测试环境的profile  ##################
##########################################################
spring:
  profiles: test
  datasource:       # mybatis 配置，使用druid数据源
    url: jdbc:mysql://192.168.4.96:3306/match_db?useUnicode=true&characterEncoding=UTF-8
    username: applicationuser
    password: 1234qwer
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20